# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# All Vagrant configuration is done here. The most common configuration
	# options are documented and commented below. For a complete reference,
	# please see the online documentation at vagrantup.com.

	config.vm.define :ha01 do |ha01_config|
	
		 	ha01_config.vm.box = "nrel/CentOS-6.5-x86_64"
			ha01_config.vm.hostname = "ha01"
			#ha01_config.vm.forward_port 80,8000

				config.vm.provider :virtualbox do |vb|
					vb.customize ["modifyvm", :id, "--memory", "256"]
					vb.customize ["modifyvm", :id, "--cpus", "1"]
				end

			ha01_config.vm.network :private_network, ip: "11.1.1.1"

	end
	
	
	config.vm.define :ha02 do |ha02_config|
	
		 	ha02_config.vm.box = "nrel/CentOS-6.5-x86_64"
			ha02_config.vm.hostname = "haproxy2"
			#ha02_config.vm.forward_port 80,8000

				config.vm.provider :virtualbox do |vb|
					vb.customize ["modifyvm", :id, "--memory", "256"]
					vb.customize ["modifyvm", :id, "--cpus", "1"]
				end

			ha02_config.vm.network :private_network, ip: "11.1.1.2"

	end
	


	config.vm.define :pup02 do |pup01_config|
	
		 	pup01_config.vm.box = "nrel/CentOS-6.5-x86_64"
			pup01_config.vm.hostname = "puppetmaster1"
			#pup01_config.vm.forward_port 80,8000

			config.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "512"]
				vb.customize ["modifyvm", :id, "--cpus", "1"]
			end

		pup01_config.vm.network :private_network, ip: "11.1.1.3"

	end


	config.vm.define :pup02 do |pup02_config|
	
		 	pup02_config.vm.box = "nrel/CentOS-6.5-x86_64"
			pup02_config.vm.hostname = "puppetmaster2"
			#pup02_config.vm.forward_port 80,8000

			config.vm.provider :virtualbox do |vb|
				vb.customize ["modifyvm", :id, "--memory", "512"]
				vb.customize ["modifyvm", :id, "--cpus", "1"]
			end

		pup02_config.vm.network :private_network, ip: "11.1.1.4"

	end



	config.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "../puppet/manifests"
		puppet.manifest_file  = "site.pp"
		puppet.module_path = "../puppet/modules"
#		#puppet.hiera_config_path = "../hiera/hiera.yaml"
	end

end



